module.exports = {
  HOME: '/',
  ACCOUNT: '/account',
  REGISTER: '/account/register',
  OTP: '/account/otp',
  LOGIN: '/account/login',
  FORGOT_PASSWORD: '/account/email-register',
  UPDATE_FORGOT_PASSWORD: '/account/forgot-password',
  DEFAULT_PRODUCT: '/product',
  PRODUCT: '/product/:categoryID',
  DEFAULT_DETAIL_PRODUCT: '/details-product',
  DETAIL_PRODUCT: '/details-product/:productID',
  USER: '/user',
  USER_INFOR: '/user/infor',
  DELIVERY: '/user/delivery',
  ADD_DELIVERY: '/user/add-delivery',
  WISH_LISTS: '/user/wish-lists',
  CHANGE_PASSWORD: '/user/change-password',
  CHECKOUT: '/checkout',
  BLOG: '/blog',
  ABOUT: '/about',
  STORE: '/store',
  CARD: '/card',
  SEARCH: '/search/:categoryID/:search',
  ORDER: '/user/order'
};
